//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_portfolio_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myporfolioEntities : DbContext
    {
        public myporfolioEntities()
            : base("name=myporfolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Banners> Tbl_Banners { get; set; }
        public virtual DbSet<Tbl_Categories> Tbl_Categories { get; set; }
        public virtual DbSet<Tbl_Contacts> Tbl_Contacts { get; set; }
        public virtual DbSet<Tbl_Educations> Tbl_Educations { get; set; }
        public virtual DbSet<Tbl_Experiences> Tbl_Experiences { get; set; }
        public virtual DbSet<Tbl_Expertises> Tbl_Expertises { get; set; }
        public virtual DbSet<Tbl_Messages> Tbl_Messages { get; set; }
        public virtual DbSet<Tbl_Procets> Tbl_Procets { get; set; }
        public virtual DbSet<Tbl_Socials> Tbl_Socials { get; set; }
        public virtual DbSet<Tbl_Testimonials> Tbl_Testimonials { get; set; }
        public virtual DbSet<TblAbout> TblAbouts { get; set; }
        public virtual DbSet<Tbl_Admins> Tbl_Admins { get; set; }
    }
}
