//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_portfolio_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Contacts
    {
        public int Contactid { get; set; }
        public string Pnone { get; set; }
        public string Email { get; set; }
    }
}
