//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_portfolio_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Procets
    {
        public int Projectid { get; set; }
        public string Name { get; set; }
        public string imageUrl { get; set; }
        public string Description { get; set; }
        public int Categoryid { get; set; }
        public string GitHubUrl { get; set; }
    
        public virtual Tbl_Categories Tbl_Categories { get; set; }
    }
}
