//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_portfolio_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Tbl_Testimonials
    {
        public int Testimonialid { get; set; }
        public string NameSurname { get; set; }
        public string Title { get; set; }
        public string imageUrl { get; set; }
        public string Comment { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile{ get; set; }
    }
}
