//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_portfolio_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Banners
    {
        public int bannerid { get; set; }
        public string title { get; set; }
        public string dicsreption { get; set; }
        public Nullable<bool> isShown { get; set; }
    }
}
